language: node_js
node_js:
  - "8"
  - "10"

# Add support for enabling Greenkeeper to 
# update the Yarn lockfile, in addition to
# the package.json file
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload